stages:
  - test

services:
  - 543682601436.dkr.ecr.us-east-1.amazonaws.com/dind:latest

variables:
  RUNNER_IMAGE_QA: 543682601436.dkr.ecr.us-east-1.amazonaws.com/cirunner:qa
  RUNNER_IMAGE_PRD: 543682601436.dkr.ecr.us-east-1.amazonaws.com/cirunner:prd
  RUNNER_IMAGE_STG: 543682601436.dkr.ecr.us-east-1.amazonaws.com/cirunner:stg
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_DRIVER: overlay2
  GIT_DEPTH: 10

before_script:
  - $(aws ecr get-login --registry-ids 543682601436 --region us-east-1 --no-include-email)

###############################################
##################    QA    ###################
###############################################

test:
  image: ${RUNNER_IMAGE_QA}
  stage: test
  script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo “$PRIVATE_KEY” | tr -d ‘\r’ > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - eval $(ssh-agent -s)
    - docker build --tag test-webaio .
    - docker run --name test-webaio -t test-webaio sh run_tests_for_docker.sh
    - docker cp test-webaio:/app/htmlcov htmlcov || true
  coverage: '/TOTAL.+?(\d+%)/'
  artifacts:
    paths:
      - htmlcov
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure